// Librería de ejercicios AMRAP — 102 ejercicios
// cat: Piernas | Glúteo | Empuje | Tracción | Core | Cardio | Movilidad
// equip: Ninguno | Mancuerna | Kettlebell | Goma | Barra | Banco | Comba
window.EXERCISES = [
// ═══════════════ PIERNAS ═══════════════
{key:'sentadilla',name:'Sentadilla libre',cat:'Piernas',equip:'Ninguno',pattern:'Dominante de rodilla',reps:'12–20 reps',
 desc:'El patrón básico de sentarse y levantarse. La base de todo el tren inferior.',
 pasos:['Pies al ancho de los hombros, puntas ligeramente hacia fuera.','Baja llevando la cadera atrás y abajo hasta que los muslos queden paralelos.','Empuja con los talones para subir y aprieta el glúteo arriba.'],
 errores:['Que las rodillas no se metan hacia dentro.','El pecho no debe caer hacia adelante.','No despegues los talones.'],
 musculos:'Cuádriceps, glúteo, core',riesgo:'Rodilla'},
{key:'sentadilla-sumo',name:'Sentadilla sumo',cat:'Piernas',equip:'Ninguno',pattern:'Dominante de rodilla',reps:'12–15 reps',
 desc:'Postura ancha que enfatiza glúteo e interior del muslo.',
 pasos:['Pies muy abiertos, puntas hacia fuera 30°.','Baja recto, rodillas siguiendo la línea de los pies.','Sube apretando glúteo y aductores.'],
 errores:['No metas las rodillas hacia dentro.','Mantén el tronco vertical.'],
 musculos:'Aductores, glúteo, cuádriceps',riesgo:'Rodilla'},
{key:'sentadilla-goblet',name:'Sentadilla goblet',cat:'Piernas',equip:'Mancuerna',pattern:'Dominante de rodilla',reps:'10–15 reps',
 desc:'Sentadilla sujetando peso al pecho, ideal para aprender la técnica.',
 pasos:['Sujeta la mancuerna vertical pegada al pecho.','Baja profundo manteniendo los codos dentro de las rodillas.','Sube empujando con todo el pie.'],
 errores:['No dejes que el peso te lleve hacia delante.','Mantén los codos altos.'],
 musculos:'Cuádriceps, glúteo, core',riesgo:'Rodilla'},
{key:'sentadilla-bulgara',name:'Sentadilla búlgara',cat:'Piernas',equip:'Banco',pattern:'Unilateral de rodilla',reps:'8–12 por pierna',
 desc:'Sentadilla a una pierna con el pie trasero elevado. Muy exigente y unilateral.',
 pasos:['Apoya el empeine trasero en un banco o silla.','Baja con la pierna delantera hasta 90°.','Empuja con el talón delantero para subir.'],
 errores:['No inclines mucho el tronco hacia delante.','La rodilla delantera no debe irse hacia dentro.'],
 musculos:'Cuádriceps, glúteo',riesgo:'Rodilla'},
{key:'sentadilla-pistol',name:'Sentadilla pistol',cat:'Piernas',equip:'Ninguno',pattern:'Unilateral de rodilla',reps:'3–8 por pierna',
 desc:'Sentadilla completa a una sola pierna. Fuerza y equilibrio de nivel avanzado.',
 pasos:['De pie sobre una pierna, la otra estirada al frente.','Baja controlado hasta abajo del todo.','Sube con fuerza sin apoyar la pierna libre.'],
 errores:['Empieza asistido (sujeto a algo) si no llegas.','No colapses la rodilla hacia dentro.'],
 musculos:'Cuádriceps, glúteo, core',riesgo:'Rodilla'},
{key:'sentadilla-pistol-asistida',name:'Pistol asistida',cat:'Piernas',equip:'Barra',pattern:'Unilateral de rodilla',reps:'6–10 por pierna',
 desc:'Progresión de la pistol sujetándote a una barra o TRX.',
 pasos:['Sujétate a una barra o poste a la altura del pecho.','Baja a una pierna usando los brazos solo para equilibrar.','Sube empujando con la pierna de apoyo.'],
 errores:['Usa los brazos lo mínimo posible.','Controla la bajada, no te dejes caer.'],
 musculos:'Cuádriceps, glúteo',riesgo:'Rodilla'},
{key:'sissy-squat',name:'Sissy squat',cat:'Piernas',equip:'Ninguno',pattern:'Dominante de rodilla',reps:'8–12 reps',
 desc:'Sentadilla inclinando el cuerpo hacia atrás. Aísla mucho el cuádriceps.',
 pasos:['De pie, sujétate a un apoyo, sube sobre las puntas.','Lleva las rodillas al frente inclinando el torso atrás en línea.','Vuelve apretando el cuádriceps.'],
 errores:['Empieza con poco rango.','Mantén cadera y tronco alineados.'],
 musculos:'Cuádriceps',riesgo:'Rodilla'},
{key:'zancada-frontal',name:'Zancada frontal',cat:'Piernas',equip:'Ninguno',pattern:'Unilateral de rodilla',reps:'8–10 por pierna',
 desc:'Paso hacia delante con descenso controlado. Fuerza y equilibrio.',
 pasos:['Da un paso largo al frente.','Baja hasta que ambas rodillas formen 90°.','Empuja para volver al centro y alterna.'],
 errores:['La rodilla no debe sobrepasar mucho la punta del pie.','Mantén el tronco erguido.'],
 musculos:'Cuádriceps, glúteo, isquios',riesgo:'Rodilla'},
{key:'zancada-trasera',name:'Zancada trasera',cat:'Piernas',equip:'Ninguno',pattern:'Unilateral de rodilla',reps:'8–10 por pierna',
 desc:'Paso atrás, más amable con la rodilla que la zancada frontal.',
 pasos:['Da un paso largo hacia atrás.','Baja hasta que la rodilla trasera casi toque el suelo.','Empuja con el talón delantero para volver.'],
 errores:['No te dejes caer de golpe.','Tronco vertical, sin inclinarte.'],
 musculos:'Glúteo, cuádriceps, isquios',riesgo:'Rodilla'},
{key:'zancada-caminando',name:'Zancada caminando',cat:'Piernas',equip:'Mancuerna',pattern:'Unilateral de rodilla',reps:'10–12 por pierna',
 desc:'Zancadas avanzando paso a paso. Añade recorrido y cardio.',
 pasos:['Avanza dando una zancada larga.','Baja hasta 90° en ambas rodillas.','Impúlsate y da el siguiente paso con la otra pierna.'],
 errores:['No des pasos cortos.','Mantén el core firme para no bambolearte.'],
 musculos:'Cuádriceps, glúteo, isquios',riesgo:'Rodilla'},
{key:'zancada-lateral',name:'Zancada lateral',cat:'Piernas',equip:'Ninguno',pattern:'Plano frontal',reps:'8–10 por lado',
 desc:'Desplazamiento lateral que trabaja el plano frontal, poco entrenado.',
 pasos:['Da un paso amplio hacia el lado.','Flexiona la pierna del paso mientras la otra queda estirada.','Empuja para volver al centro.'],
 errores:['Mantén las puntas al frente.','No redondees la espalda al bajar.'],
 musculos:'Aductores, glúteo, cuádriceps',riesgo:'Rodilla · Cadera'},
{key:'step-up',name:'Subida a cajón',cat:'Piernas',equip:'Banco',pattern:'Unilateral de rodilla',reps:'10–12 por pierna',
 desc:'Subir a una superficie elevada. Funcional y unilateral.',
 pasos:['Apoya todo el pie en el cajón.','Sube empujando con el talón de arriba, sin impulso del pie de abajo.','Baja controlado.'],
 errores:['No te impulses con la pierna de abajo.','Rodilla alineada con el pie.'],
 musculos:'Cuádriceps, glúteo',riesgo:'Rodilla'},
{key:'nordic-curl',name:'Nordic curl',cat:'Piernas',equip:'Ninguno',pattern:'Dominante de cadera',reps:'4–8 reps',
 desc:'Excéntrico de isquios de rodillas. Uno de los mejores para prevenir lesiones.',
 pasos:['De rodillas con los tobillos anclados bajo algo firme.','Baja el tronco al frente resistiendo con los isquios.','Ayúdate con las manos abajo y vuelve.'],
 errores:['Controla la bajada al máximo.','No dobles la cadera: cuerpo recto.'],
 musculos:'Isquiotibiales',riesgo:'Rodilla'},
{key:'gemelos',name:'Elevación de talón',cat:'Piernas',equip:'Ninguno',pattern:'Aislamiento',reps:'15–20 reps',
 desc:'Aislamiento de gemelo. Simple y muy efectivo.',
 pasos:['De pie, sube sobre las puntas todo lo que puedas.','Aprieta el gemelo arriba 1 segundo.','Baja lento hasta estirar.'],
 errores:['No rebotes: controla la bajada.','Sube el máximo recorrido.'],
 musculos:'Gemelo, sóleo',riesgo:'Tobillo'},
{key:'gemelos-escalon',name:'Gemelo en escalón',cat:'Piernas',equip:'Banco',pattern:'Aislamiento',reps:'15–20 reps',
 desc:'Elevación de talón con más rango dejando caer el talón bajo el escalón.',
 pasos:['Metatarsos en el borde de un escalón, talones colgando.','Baja los talones por debajo del escalón.','Sube al máximo sobre las puntas.'],
 errores:['Sujétate para equilibrar.','Rango completo, sin rebotes.'],
 musculos:'Gemelo, sóleo',riesgo:'Tobillo'},
{key:'sentadilla-pared',name:'Sentadilla isométrica en pared',cat:'Piernas',equip:'Ninguno',pattern:'Isométrico',reps:'30–60 seg',
 desc:'Isometría en 90°. Resistencia de cuádriceps sin impacto.',
 pasos:['Apoya la espalda en la pared y baja hasta muslos paralelos.','Rodillas sobre los tobillos, 90°.','Mantén la posición respirando normal.'],
 errores:['No dejes que las rodillas pasen los pies.','Espalda pegada del todo.'],
 musculos:'Cuádriceps, glúteo',riesgo:'Rodilla'},
{key:'thruster',name:'Thruster',cat:'Piernas',equip:'Mancuerna',pattern:'Combinado',reps:'10–15 reps',
 desc:'Sentadilla + press de hombros en un solo movimiento. Cuerpo entero.',
 pasos:['Mancuernas a los hombros, baja a sentadilla.','Sube explosivo y encadena un press por encima de la cabeza.','Baja el peso a los hombros y repite.'],
 errores:['Usa el impulso de piernas para el press.','No arquees la lumbar arriba.'],
 musculos:'Cuádriceps, glúteo, hombro',riesgo:'Hombro · Rodilla'},
// ═══════════════ GLÚTEO ═══════════════
{key:'puente-gluteo',name:'Puente de glúteo',cat:'Glúteo',equip:'Ninguno',pattern:'Dominante de cadera',reps:'15–20 reps',
 desc:'Extensión de cadera tumbado. Aísla el glúteo y cuida la lumbar.',
 pasos:['Boca arriba, rodillas dobladas y pies cerca del glúteo.','Empuja con los talones y eleva la cadera.','Aprieta el glúteo arriba y baja controlado.'],
 errores:['No empujes con la lumbar.','No hiperextiendas arriba.'],
 musculos:'Glúteo mayor, isquios',riesgo:'Lumbar'},
{key:'puente-una-pierna',name:'Puente a una pierna',cat:'Glúteo',equip:'Ninguno',pattern:'Unilateral de cadera',reps:'10–12 por pierna',
 desc:'Puente unilateral. El doble de carga sobre un solo glúteo.',
 pasos:['Puente con una pierna estirada al frente.','Sube la cadera empujando con el talón apoyado.','Mantén la cadera nivelada arriba.'],
 errores:['No dejes caer la cadera del lado libre.','Aprieta el glúteo, no la lumbar.'],
 musculos:'Glúteo mayor, isquios',riesgo:'Lumbar'},
{key:'hip-thrust',name:'Hip thrust',cat:'Glúteo',equip:'Banco',pattern:'Dominante de cadera',reps:'10–15 reps',
 desc:'Puente con la espalda apoyada en un banco. Máxima activación de glúteo.',
 pasos:['Apoya la parte alta de la espalda en un banco, peso sobre la cadera.','Sube hasta que el tronco quede horizontal.','Aprieta el glúteo 1 seg y baja.'],
 errores:['No arquees la lumbar arriba.','Barbilla al pecho.'],
 musculos:'Glúteo mayor, isquios',riesgo:'Lumbar'},
{key:'patada-gluteo',name:'Patada de glúteo',cat:'Glúteo',equip:'Ninguno',pattern:'Unilateral de cadera',reps:'12–15 por pierna',
 desc:'En cuadrupedia, extensión de cadera aislada por pierna.',
 pasos:['A cuatro apoyos, espalda neutra.','Lleva un talón hacia el techo con la rodilla a 90°.','Aprieta el glúteo arriba y baja sin tocar el suelo.'],
 errores:['No arquees la lumbar.','No gires la cadera.'],
 musculos:'Glúteo mayor',riesgo:'Lumbar'},
{key:'patada-goma',name:'Patada de glúteo con goma',cat:'Glúteo',equip:'Goma',pattern:'Unilateral de cadera',reps:'15 por pierna',
 desc:'Extensión de cadera con resistencia de banda para más tensión.',
 pasos:['Banda alrededor del pie y sujeta con las manos en cuadrupedia.','Empuja el pie hacia atrás estirando la pierna.','Vuelve controlando la banda.'],
 errores:['No arquees la lumbar.','Extensión desde el glúteo, no la espalda.'],
 musculos:'Glúteo mayor',riesgo:'Lumbar'},
{key:'abduccion-cadera',name:'Abducción de cadera',cat:'Glúteo',equip:'Goma',pattern:'Plano frontal',reps:'15 por lado',
 desc:'Elevación lateral de pierna. Activa el glúteo medio, clave para la rodilla.',
 pasos:['Banda por encima de las rodillas, tumbado de lado o de pie.','Abre la pierna hacia fuera controlado.','Vuelve sin dejar de tensar la banda.'],
 errores:['No gires la cadera atrás.','Movimiento lento, sin impulso.'],
 musculos:'Glúteo medio',riesgo:'Cadera'},
{key:'almeja',name:'Almeja (clam)',cat:'Glúteo',equip:'Goma',pattern:'Plano frontal',reps:'15–20 por lado',
 desc:'Apertura de rodillas tumbado de lado. Activación pura de glúteo medio.',
 pasos:['Tumbado de lado, rodillas dobladas y banda sobre ellas.','Abre la rodilla de arriba sin mover la pelvis.','Cierra controlado.'],
 errores:['No ruedes la cadera hacia atrás.','Pies juntos todo el rato.'],
 musculos:'Glúteo medio',riesgo:'Cadera'},
{key:'monster-walk',name:'Monster walk',cat:'Glúteo',equip:'Goma',pattern:'Plano frontal',reps:'10 pasos x 3',
 desc:'Caminata lateral con banda. Enciende el glúteo medio; gran calentamiento.',
 pasos:['Banda en los tobillos o rodillas, semi-sentadilla.','Da pasos laterales manteniendo tensión.','No juntes del todo los pies.'],
 errores:['No subas y bajes el tronco.','Mantén tensión constante en la banda.'],
 musculos:'Glúteo medio',riesgo:'Cadera'},
{key:'peso-muerto-rumano',name:'Peso muerto rumano',cat:'Glúteo',equip:'Mancuerna',pattern:'Bisagra de cadera',reps:'10–12 reps',
 desc:'Bisagra de cadera. El mejor ejercicio para isquios y glúteo.',
 pasos:['De pie, peso frente a los muslos, rodillas algo flexionadas.','Lleva la cadera atrás bajando el peso pegado a la pierna.','Sube empujando la cadera al frente.'],
 errores:['No redondees la espalda.','No es sentadilla: es de cadera.'],
 musculos:'Isquios, glúteo, lumbar',riesgo:'Lumbar'},
{key:'peso-muerto-una-pierna',name:'Peso muerto a una pierna',cat:'Glúteo',equip:'Mancuerna',pattern:'Bisagra unilateral',reps:'8–10 por pierna',
 desc:'Bisagra unilateral. Fuerza de glúteo, isquios y mucho equilibrio.',
 pasos:['Sobre una pierna, baja el peso mientras la pierna libre sube atrás.','Cuerpo en línea como un balancín.','Sube apretando el glúteo.'],
 errores:['No redondees la espalda.','Cadera nivelada, sin abrirse.'],
 musculos:'Isquios, glúteo medio, core',riesgo:'Lumbar'},
{key:'good-morning-goma',name:'Good morning con goma',cat:'Glúteo',equip:'Goma',pattern:'Bisagra de cadera',reps:'12–15 reps',
 desc:'Bisagra de cadera con banda bajo los pies y sobre la nuca.',
 pasos:['Banda bajo los pies y sobre los hombros.','Inclina el tronco al frente con la espalda recta.','Sube empujando la cadera.'],
 errores:['No redondees la espalda.','Rodillas ligeramente flexionadas.'],
 musculos:'Isquios, glúteo, lumbar',riesgo:'Lumbar'},
// ═══════════════ EMPUJE ═══════════════
{key:'flexiones',name:'Flexiones',cat:'Empuje',equip:'Ninguno',pattern:'Empuje horizontal',reps:'6–15 reps',
 desc:'Empuje horizontal por excelencia. Cuerpo en una sola línea.',
 pasos:['Manos bajo los hombros, cuerpo recto.','Baja doblando los codos a 45° del torso.','Empuja hasta estirar sin bloquear.'],
 errores:['No dejes caer la cadera.','No abras los codos a 90°.','Baja todo el cuerpo a la vez.'],
 musculos:'Pectoral, tríceps, deltoides',riesgo:'Hombro · Muñeca'},
{key:'flexiones-rodillas',name:'Flexiones de rodillas',cat:'Empuje',equip:'Ninguno',pattern:'Empuje horizontal',reps:'8–15 reps',
 desc:'Versión accesible apoyando las rodillas. Ideal para empezar.',
 pasos:['Apoya las rodillas, cuerpo recto de la cabeza a las rodillas.','Baja el pecho controlado.','Empuja para volver.'],
 errores:['No hundas la cadera.','Mantén la línea cabeza-rodillas.'],
 musculos:'Pectoral, tríceps',riesgo:'Muñeca'},
{key:'flexiones-inclinadas',name:'Flexiones inclinadas',cat:'Empuje',equip:'Banco',pattern:'Empuje horizontal',reps:'8–15 reps',
 desc:'Manos elevadas: versión más accesible para ganar fuerza.',
 pasos:['Apoya las manos en un banco o pared.','Baja el pecho hacia el apoyo con el cuerpo recto.','Empuja para volver.'],
 errores:['No hundas la cadera.','Cuanto más alto el apoyo, más fácil.'],
 musculos:'Pectoral, tríceps',riesgo:'Hombro'},
{key:'flexiones-declinadas',name:'Flexiones declinadas',cat:'Empuje',equip:'Banco',pattern:'Empuje horizontal',reps:'6–12 reps',
 desc:'Pies elevados: más carga sobre el pecho superior y el hombro.',
 pasos:['Apoya los pies en un banco, manos en el suelo.','Baja controlando el pecho hacia el suelo.','Empuja manteniendo la línea del cuerpo.'],
 errores:['No arquees la lumbar.','Núcleo firme.'],
 musculos:'Pectoral superior, deltoides, tríceps',riesgo:'Hombro · Muñeca'},
{key:'flexiones-diamante',name:'Flexiones diamante',cat:'Empuje',equip:'Ninguno',pattern:'Empuje horizontal',reps:'6–12 reps',
 desc:'Manos juntas formando un rombo. Máximo trabajo de tríceps.',
 pasos:['Junta las manos bajo el pecho, índices y pulgares tocándose.','Baja con los codos pegados al cuerpo.','Empuja hasta estirar.'],
 errores:['No abras los codos.','Cadera en línea.'],
 musculos:'Tríceps, pectoral interior',riesgo:'Muñeca · Codo'},
{key:'flexiones-arquero',name:'Flexiones arquero',cat:'Empuje',equip:'Ninguno',pattern:'Empuje unilateral',reps:'4–8 por lado',
 desc:'Flexión cargando el peso en un brazo. Progresión hacia la flexión a una mano.',
 pasos:['Manos muy abiertas.','Baja hacia un lado doblando ese brazo, el otro estirado.','Empuja y alterna de lado.'],
 errores:['Mantén el cuerpo recto.','El brazo estirado solo asiste.'],
 musculos:'Pectoral, tríceps, core',riesgo:'Hombro · Muñeca'},
{key:'pike-pushup',name:'Pike push-up',cat:'Empuje',equip:'Ninguno',pattern:'Empuje vertical',reps:'6–12 reps',
 desc:'Flexión en V invertida, precursora del press de hombro a pulso.',
 pasos:['Posición de V invertida, cadera arriba.','Baja la cabeza hacia el suelo doblando los codos.','Empuja hacia arriba.'],
 errores:['Mantén la cadera alta.','Codos no demasiado abiertos.'],
 musculos:'Deltoides, tríceps',riesgo:'Hombro · Muñeca'},
{key:'handstand-pared',name:'Pino contra pared',cat:'Empuje',equip:'Ninguno',pattern:'Isométrico vertical',reps:'20–45 seg',
 desc:'Sostén invertido apoyado en la pared. Fuerza y control de hombro.',
 pasos:['Sube a pino con la espalda o el pecho hacia la pared.','Aprieta abdomen y glúteo, cuerpo recto.','Mantén el tiempo respirando.'],
 errores:['No arquees la lumbar.','Manos firmes, dedos activos.'],
 musculos:'Hombro, tríceps, core',riesgo:'Hombro · Muñeca'},
{key:'wall-walk',name:'Wall walk',cat:'Empuje',equip:'Ninguno',pattern:'Empuje vertical',reps:'3–6 reps',
 desc:'Caminar con las manos hacia la pared hasta el pino. Fuerza y control.',
 pasos:['Empieza en plancha con los pies en la pared.','Camina con las manos hacia la pared subiendo los pies.','Baja controlado a la posición inicial.'],
 errores:['No arquees la lumbar.','Baja tan controlado como subes.'],
 musculos:'Hombro, core, tríceps',riesgo:'Hombro · Muñeca'},
{key:'press-hombros',name:'Press de hombros',cat:'Empuje',equip:'Mancuerna',pattern:'Empuje vertical',reps:'8–12 reps',
 desc:'Empuje vertical sobre la cabeza. Fuerza de hombro y tríceps.',
 pasos:['Mancuernas a la altura de los hombros, palmas al frente.','Aprieta el core y empuja hacia arriba.','Baja controlado a las orejas.'],
 errores:['No arquees la lumbar.','No subas los hombros a las orejas.'],
 musculos:'Deltoides, tríceps, trapecio',riesgo:'Hombro'},
{key:'press-arnold',name:'Press Arnold',cat:'Empuje',equip:'Mancuerna',pattern:'Empuje vertical',reps:'8–12 reps',
 desc:'Press de hombro con rotación. Trabaja el deltoides en todo su rango.',
 pasos:['Empieza con las palmas mirándote a la altura del pecho.','Sube rotando las palmas hasta quedar al frente arriba.','Baja invirtiendo el giro.'],
 errores:['No uses impulso de piernas.','Controla la rotación.'],
 musculos:'Deltoides, tríceps',riesgo:'Hombro'},
{key:'press-goma',name:'Press de hombro con goma',cat:'Empuje',equip:'Goma',pattern:'Empuje vertical',reps:'12–15 reps',
 desc:'Press vertical con banda pisada. Perfecto para viajar.',
 pasos:['Pisa la banda, manos a la altura de los hombros.','Empuja hacia arriba hasta estirar los brazos.','Baja controlando la banda.'],
 errores:['No arquees la lumbar.','Tensión constante en la banda.'],
 musculos:'Deltoides, tríceps',riesgo:'Hombro'},
{key:'elevaciones-laterales',name:'Elevaciones laterales',cat:'Empuje',equip:'Mancuerna',pattern:'Aislamiento',reps:'12–15 reps',
 desc:'Aislamiento del deltoides lateral, el que da anchura al hombro.',
 pasos:['De pie, mancuernas a los lados, codos casi rectos.','Sube los brazos hasta la horizontal.','Baja lento sin balanceo.'],
 errores:['No uses impulso.','No pases mucho de la horizontal.'],
 musculos:'Deltoides lateral',riesgo:'Hombro'},
{key:'elevaciones-frontales',name:'Elevaciones frontales',cat:'Empuje',equip:'Mancuerna',pattern:'Aislamiento',reps:'12–15 reps',
 desc:'Elevación al frente para el deltoides anterior.',
 pasos:['Peso frente a los muslos, brazos rectos.','Sube al frente hasta la altura de los ojos.','Baja controlado.'],
 errores:['No balancees el tronco.','No subas por encima de los hombros.'],
 musculos:'Deltoides anterior',riesgo:'Hombro'},
{key:'fondos-banco',name:'Fondos en banco',cat:'Empuje',equip:'Banco',pattern:'Empuje vertical',reps:'8–15 reps',
 desc:'Empuje inverso apoyado en un banco. Aísla el tríceps.',
 pasos:['Manos en el borde del banco, glúteo por delante.','Baja doblando los codos hacia atrás.','Empuja hasta estirar los brazos.'],
 errores:['No bajes demasiado (cuida el hombro).','Codos atrás, no hacia fuera.'],
 musculos:'Tríceps, deltoides anterior',riesgo:'Hombro'},
{key:'fondos-paralelas',name:'Fondos en paralelas',cat:'Empuje',equip:'Barra',pattern:'Empuje vertical',reps:'6–12 reps',
 desc:'Fondos en barras paralelas del parque. Gran ejercicio de empuje.',
 pasos:['Sostente en las paralelas con los brazos estirados.','Baja doblando los codos hasta ~90°.','Empuja hasta estirar.'],
 errores:['No bajes por debajo de lo cómodo para el hombro.','Ligera inclinación al frente para el pecho.'],
 musculos:'Pectoral inferior, tríceps, hombro',riesgo:'Hombro'},
{key:'extension-triceps',name:'Extensión de tríceps',cat:'Empuje',equip:'Mancuerna',pattern:'Aislamiento',reps:'10–15 reps',
 desc:'Extensión por encima de la cabeza, aísla la cabeza larga del tríceps.',
 pasos:['Sujeta una mancuerna con ambas manos sobre la cabeza.','Baja el peso por detrás doblando solo los codos.','Sube estirando los brazos.'],
 errores:['Codos apuntando al frente.','No arquees la lumbar.'],
 musculos:'Tríceps',riesgo:'Codo · Hombro'},
// ═══════════════ TRACCIÓN ═══════════════
{key:'dominadas-pronas',name:'Dominadas pronas',cat:'Tracción',equip:'Barra',pattern:'Tracción vertical',reps:'4–10 reps',
 desc:'Tracción vertical con agarre prono. El rey de la espalda.',
 pasos:['Cuélgate con las palmas al frente, más anchas que los hombros.','Tira llevando el pecho a la barra.','Baja controlado hasta estirar los brazos.'],
 errores:['No des tirones con las piernas.','Aprieta las escápulas al iniciar.'],
 musculos:'Dorsal, romboides, bíceps',riesgo:'Hombro · Codo'},
{key:'dominadas-supinas',name:'Dominadas supinas',cat:'Tracción',equip:'Barra',pattern:'Tracción vertical',reps:'4–10 reps',
 desc:'Agarre supino (chin-up). Más participación de bíceps, algo más fácil.',
 pasos:['Cuélgate con las palmas hacia ti, al ancho de los hombros.','Tira hasta pasar la barbilla la barra.','Baja controlado.'],
 errores:['No te balancees.','Rango completo, brazos estirados abajo.'],
 musculos:'Dorsal, bíceps',riesgo:'Codo · Hombro'},
{key:'dominadas-neutras',name:'Dominadas neutras',cat:'Tracción',equip:'Barra',pattern:'Tracción vertical',reps:'4–10 reps',
 desc:'Agarre neutro (palmas enfrentadas). Más amable con el hombro.',
 pasos:['Cuélgate con las palmas enfrentadas.','Tira llevando el pecho arriba.','Baja controlado.'],
 errores:['No des tirones.','Escápulas activas.'],
 musculos:'Dorsal, braquial, bíceps',riesgo:'Hombro'},
{key:'dominadas-negativas',name:'Dominadas negativas',cat:'Tracción',equip:'Barra',pattern:'Tracción vertical',reps:'4–6 reps',
 desc:'Solo la fase de bajada. La mejor progresión para tu primera dominada.',
 pasos:['Sube con un salto hasta la barbilla sobre la barra.','Baja lo más lento posible (3–5 seg).','Repite desde arriba.'],
 errores:['Cuanto más lento bajes, mejor.','Controla hasta estirar del todo.'],
 musculos:'Dorsal, bíceps',riesgo:'Hombro · Codo'},
{key:'remo-invertido',name:'Remo invertido (australian)',cat:'Tracción',equip:'Barra',pattern:'Tracción horizontal',reps:'8–15 reps',
 desc:'Tracción horizontal bajo una barra baja. Progresión clave hacia dominadas.',
 pasos:['Túmbate bajo una barra a la altura del pecho, cuerpo recto.','Tira del pecho hacia la barra.','Baja controlado.'],
 errores:['No hundas la cadera.','Aprieta las escápulas arriba.'],
 musculos:'Dorsal, romboides, bíceps',riesgo:'Hombro'},
{key:'muscle-up',name:'Muscle-up',cat:'Tracción',equip:'Barra',pattern:'Combinado',reps:'2–6 reps',
 desc:'Dominada explosiva + transición a fondo por encima de la barra. Avanzado.',
 pasos:['Tira explosivo llevando el pecho por encima de la barra.','Gira las muñecas y pasa el torso por encima.','Empuja hasta estirar los brazos arriba.'],
 errores:['Domina antes dominadas y fondos.','No fuerces la transición sin fuerza suficiente.'],
 musculos:'Dorsal, pectoral, tríceps',riesgo:'Hombro · Codo'},
{key:'dead-hang',name:'Colgarse en barra',cat:'Tracción',equip:'Barra',pattern:'Isométrico',reps:'20–45 seg',
 desc:'Colgarse pasivo. Fortalece el agarre y descomprime la columna.',
 pasos:['Cuélgate de la barra con los brazos estirados.','Hombros activos, sin encogerte del todo.','Respira y aguanta el tiempo objetivo.'],
 errores:['No aguantes con el hombro totalmente pasivo.','Suelta antes de perder el agarre por completo.'],
 musculos:'Antebrazo, dorsal, hombro',riesgo:'Hombro'},
{key:'remo-mancuerna',name:'Remo con mancuerna',cat:'Tracción',equip:'Mancuerna',pattern:'Tracción horizontal',reps:'10–12 por brazo',
 desc:'Tracción horizontal a un brazo. Base de la espalda.',
 pasos:['Apoya rodilla y mano en el banco, espalda plana.','Tira del peso a la cadera pegando el codo al cuerpo.','Baja controlado.'],
 errores:['No gires el tronco.','Codo atrás, no hacia fuera.'],
 musculos:'Dorsal, romboides, bíceps',riesgo:'Lumbar · Hombro'},
{key:'remo-inclinado',name:'Remo inclinado',cat:'Tracción',equip:'Mancuerna',pattern:'Tracción horizontal',reps:'10–12 reps',
 desc:'Tracción a dos brazos con el tronco inclinado. Espalda media.',
 pasos:['Inclina el tronco a ~45° con la espalda recta.','Tira del peso hacia el abdomen.','Baja controlado.'],
 errores:['No redondees la espalda.','No te levantes con impulso.'],
 musculos:'Dorsal, romboides, trapecio',riesgo:'Lumbar'},
{key:'remo-goma',name:'Remo con goma',cat:'Tracción',equip:'Goma',pattern:'Tracción horizontal',reps:'12–15 reps',
 desc:'Tracción horizontal con banda anclada. Perfecto para viajar.',
 pasos:['Ancla la banda al frente a la altura del pecho.','Tira de los codos hacia atrás pegados al cuerpo.','Vuelve controlando la banda.'],
 errores:['Aprieta las escápulas.','No encojas los hombros.'],
 musculos:'Dorsal, romboides, bíceps',riesgo:'Hombro'},
{key:'remo-renegado',name:'Remo renegado',cat:'Tracción',equip:'Mancuerna',pattern:'Combinado',reps:'6–10 por lado',
 desc:'Remo desde posición de plancha. Espalda y core a la vez.',
 pasos:['En plancha alta sujetando las mancuernas.','Rema una mancuerna a la cadera sin girar la cadera.','Alterna manteniendo el cuerpo firme.'],
 errores:['No dejes que la cadera rote.','Pies algo abiertos para estabilidad.'],
 musculos:'Dorsal, core, hombro',riesgo:'Lumbar · Muñeca'},
{key:'curl-biceps',name:'Curl de bíceps',cat:'Tracción',equip:'Mancuerna',pattern:'Aislamiento',reps:'10–12 reps',
 desc:'Flexión de codo clásica para el bíceps.',
 pasos:['De pie, mancuernas a los lados, palmas al frente.','Sube doblando el codo sin mover el hombro.','Baja lento hasta estirar.'],
 errores:['No balancees el cuerpo.','Codos pegados al costado.'],
 musculos:'Bíceps, antebrazo',riesgo:'Codo'},
{key:'curl-martillo',name:'Curl martillo',cat:'Tracción',equip:'Mancuerna',pattern:'Aislamiento',reps:'10–12 reps',
 desc:'Curl con agarre neutro. Bíceps y braquial (grosor del brazo).',
 pasos:['Palmas mirándose (agarre de martillo).','Sube sin girar la muñeca.','Baja controlado.'],
 errores:['No uses impulso.','Muñecas firmes.'],
 musculos:'Bíceps, braquial, antebrazo',riesgo:'Codo'},
{key:'curl-goma',name:'Curl con goma',cat:'Tracción',equip:'Goma',pattern:'Aislamiento',reps:'12–15 reps',
 desc:'Curl de bíceps con banda pisada. Tensión constante.',
 pasos:['Pisa la banda, agárrala con las palmas al frente.','Sube doblando el codo.','Baja controlando la banda.'],
 errores:['Codos pegados.','No pierdas la tensión abajo.'],
 musculos:'Bíceps, antebrazo',riesgo:'Codo'},
{key:'face-pull',name:'Face pull con goma',cat:'Tracción',equip:'Goma',pattern:'Tracción facial',reps:'15–20 reps',
 desc:'Tracción hacia la cara. Salud de hombro y postura.',
 pasos:['Ancla la banda a la altura de la cara.','Tira hacia la frente abriendo los codos.','Aprieta las escápulas y vuelve.'],
 errores:['No encojas los hombros.','Codos altos todo el recorrido.'],
 musculos:'Deltoides posterior, trapecio, rotadores',riesgo:'Hombro'},
{key:'pull-apart',name:'Pull-apart con goma',cat:'Tracción',equip:'Goma',pattern:'Aislamiento',reps:'15–20 reps',
 desc:'Apertura de banda al frente. Espalda alta y rotadores.',
 pasos:['Sujeta la banda con los brazos al frente a la altura del pecho.','Ábrela llevando las manos a los lados.','Aprieta las escápulas y vuelve.'],
 errores:['No arquees la lumbar.','Brazos a la altura del pecho.'],
 musculos:'Deltoides posterior, romboides',riesgo:'Hombro'},
{key:'superman',name:'Superman',cat:'Tracción',equip:'Ninguno',pattern:'Extensión',reps:'12–15 reps',
 desc:'Extensión lumbar tumbado boca abajo. Fortalece la cadena posterior.',
 pasos:['Boca abajo, brazos estirados al frente.','Eleva brazos y piernas a la vez.','Aprieta arriba 1 seg y baja lento.'],
 errores:['No fuerces el cuello.','Movimiento corto y controlado.'],
 musculos:'Erectores espinales, glúteo',riesgo:'Lumbar'},
// ═══════════════ CORE ═══════════════
{key:'plancha',name:'Plancha',cat:'Core',equip:'Ninguno',pattern:'Anti-extensión',reps:'20–45 seg',
 desc:'Isométrico de estabilidad. La línea perfecta importa más que el tiempo.',
 pasos:['Antebrazos bajo los hombros, puntas de los pies.','Línea recta de cabeza a talones.','Aprieta abdomen y glúteo, respira normal.'],
 errores:['No hundas la cadera.','No subas el culo en pico.','No aguantes la respiración.'],
 musculos:'Transverso, recto abdominal, glúteo',riesgo:'Lumbar · Hombro'},
{key:'plancha-lateral',name:'Plancha lateral',cat:'Core',equip:'Ninguno',pattern:'Anti-flexión lateral',reps:'20–40 seg por lado',
 desc:'Isométrico para oblicuos y estabilizadores de cadera.',
 pasos:['Apóyate en un antebrazo, cuerpo de lado.','Eleva la cadera formando una línea recta.','Mantén y cambia de lado.'],
 errores:['No dejes caer la cadera.','Hombro sobre el codo.'],
 musculos:'Oblicuos, glúteo medio',riesgo:'Hombro'},
{key:'plancha-updown',name:'Plancha up-down',cat:'Core',equip:'Ninguno',pattern:'Anti-rotación',reps:'30–45 seg',
 desc:'Pasar de antebrazos a manos y volver. Core dinámico y hombro.',
 pasos:['Desde plancha de antebrazos, sube a plancha de manos.','Baja de nuevo a antebrazos alternando el brazo que inicia.','Mantén la cadera lo más estable posible.'],
 errores:['No balancees la cadera.','Manos y codos bajo los hombros.'],
 musculos:'Core, hombro, tríceps',riesgo:'Muñeca · Hombro'},
{key:'copenhagen',name:'Plancha Copenhagen',cat:'Core',equip:'Banco',pattern:'Anti-flexión lateral',reps:'15–30 seg por lado',
 desc:'Plancha lateral con la pierna de arriba en un banco. Aductores y core.',
 pasos:['Plancha lateral con el pie de arriba sobre un banco.','Eleva la cadera y la pierna de abajo.','Mantén la línea y respira.'],
 errores:['Empieza con la rodilla apoyada si es muy duro.','No dejes caer la cadera.'],
 musculos:'Aductores, oblicuos',riesgo:'Ingle'},
{key:'crunch',name:'Crunch',cat:'Core',equip:'Ninguno',pattern:'Flexión de tronco',reps:'15–20 reps',
 desc:'Flexión corta de tronco. Aísla el recto abdominal superior.',
 pasos:['Boca arriba, rodillas dobladas, manos en las sienes.','Sube los hombros despegando las escápulas.','Baja controlado sin apoyar del todo.'],
 errores:['No tires del cuello.','Movimiento corto.'],
 musculos:'Recto abdominal',riesgo:'Cuello'},
{key:'crunch-bicicleta',name:'Crunch bicicleta',cat:'Core',equip:'Ninguno',pattern:'Rotación',reps:'20–30 reps',
 desc:'Crunch con rotación y pedaleo. Trabaja oblicuos y recto.',
 pasos:['Boca arriba, lleva codo hacia la rodilla contraria.','Alterna estirando la otra pierna.','Movimiento fluido y controlado.'],
 errores:['No tires del cuello.','Lumbar pegada al suelo.'],
 musculos:'Oblicuos, recto abdominal',riesgo:'Cuello · Lumbar'},
{key:'reverse-crunch',name:'Crunch inverso',cat:'Core',equip:'Ninguno',pattern:'Flexión de tronco',reps:'12–15 reps',
 desc:'Lleva las rodillas al pecho enrollando la pelvis. Abdomen inferior.',
 pasos:['Boca arriba, rodillas a 90°.','Enrolla la pelvis llevando las rodillas al pecho.','Baja controlado sin arquear.'],
 errores:['No uses impulso.','El movimiento es de pelvis, no de piernas.'],
 musculos:'Recto abdominal inferior',riesgo:'Lumbar'},
{key:'elevacion-piernas',name:'Elevación de piernas',cat:'Core',equip:'Ninguno',pattern:'Flexión de cadera',reps:'12–15 reps',
 desc:'Elevación de piernas tumbado. Enfoca el abdomen inferior.',
 pasos:['Boca arriba, piernas rectas y manos bajo el glúteo.','Sube las piernas hasta la vertical.','Baja lento sin tocar el suelo.'],
 errores:['No arquees la lumbar.','Baja controlado.'],
 musculos:'Recto abdominal inferior, flexores',riesgo:'Lumbar'},
{key:'elevacion-colgado',name:'Elevación de piernas colgado',cat:'Core',equip:'Barra',pattern:'Flexión de cadera',reps:'8–15 reps',
 desc:'Colgado de la barra, sube las rodillas o piernas. Abdomen y agarre.',
 pasos:['Cuélgate de la barra sin balancearte.','Sube las rodillas (o piernas rectas) hacia el pecho.','Baja controlado sin coger impulso.'],
 errores:['No te balancees.','Controla la bajada.'],
 musculos:'Abdomen, flexores, agarre',riesgo:'Hombro · Lumbar'},
{key:'toes-to-bar',name:'Toes to bar',cat:'Core',equip:'Barra',pattern:'Flexión de cadera',reps:'5–10 reps',
 desc:'Colgado, lleva las puntas de los pies a la barra. Avanzado.',
 pasos:['Cuélgate de la barra, hombros activos.','Sube las piernas rectas hasta tocar la barra con los pies.','Baja controlado.'],
 errores:['Domina antes la elevación de rodillas.','Evita el balanceo excesivo.'],
 musculos:'Abdomen, flexores, dorsal',riesgo:'Hombro · Lumbar'},
{key:'russian-twist',name:'Russian twist',cat:'Core',equip:'Ninguno',pattern:'Rotación',reps:'20–30 reps',
 desc:'Rotación de tronco sentado. Trabaja oblicuos.',
 pasos:['Sentado, tronco algo atrás y pies elevados.','Gira el tronco tocando el suelo a cada lado.','Pecho arriba.'],
 errores:['Gira desde el tronco.','No redondees la espalda.'],
 musculos:'Oblicuos, recto abdominal',riesgo:'Lumbar'},
{key:'v-ups',name:'V-ups',cat:'Core',equip:'Ninguno',pattern:'Flexión de tronco',reps:'10–15 reps',
 desc:'Sube tronco y piernas a la vez formando una V. Abdomen completo.',
 pasos:['Boca arriba, brazos y piernas estirados.','Sube a la vez tronco y piernas tocando los pies.','Baja controlado.'],
 errores:['No tires del cuello.','Baja sin dejarte caer.'],
 musculos:'Recto abdominal, flexores',riesgo:'Lumbar'},
{key:'flutter-kicks',name:'Flutter kicks',cat:'Core',equip:'Ninguno',pattern:'Anti-extensión',reps:'30–45 seg',
 desc:'Aleteo de piernas rectas. Abdomen inferior y resistencia.',
 pasos:['Boca arriba, piernas rectas y algo elevadas.','Alterna subiendo y bajando las piernas en aleteo corto.','Lumbar pegada al suelo.'],
 errores:['No arquees la lumbar.','Manos bajo el glúteo si molesta.'],
 musculos:'Recto abdominal inferior, flexores',riesgo:'Lumbar'},
{key:'mountain-climbers',name:'Mountain climbers',cat:'Core',equip:'Ninguno',pattern:'Anti-extensión',reps:'30–45 seg',
 desc:'Escaladores desde plancha. Core dinámico con pulso alto.',
 pasos:['En plancha alta, manos bajo los hombros.','Lleva una rodilla al pecho y alterna rápido.','Cadera baja y estable.'],
 errores:['No subas el culo.','Hombros sobre las muñecas.'],
 musculos:'Core, flexores, hombro',riesgo:'Muñeca'},
{key:'dead-bug',name:'Dead bug',cat:'Core',equip:'Ninguno',pattern:'Anti-extensión',reps:'10–12 por lado',
 desc:'Anti-extensión tumbado. Enseña a estabilizar la lumbar.',
 pasos:['Boca arriba, brazos y rodillas a 90°.','Estira brazo y pierna contrarios sin tocar el suelo.','Vuelve manteniendo la lumbar pegada.'],
 errores:['La lumbar no debe despegarse.','Movimiento lento.'],
 musculos:'Transverso, recto abdominal',riesgo:'Lumbar (protege)'},
{key:'bird-dog',name:'Bird dog',cat:'Core',equip:'Ninguno',pattern:'Anti-rotación',reps:'10–12 por lado',
 desc:'Estabilidad en cuadrupedia. Core y espalda sin carga axial.',
 pasos:['A cuatro apoyos, espalda neutra.','Estira brazo y pierna contrarios en línea.','Aprieta y vuelve sin perder el equilibrio.'],
 errores:['No arquees la lumbar.','No gires la cadera.'],
 musculos:'Erectores, glúteo, core',riesgo:'Lumbar'},
{key:'hollow-hold',name:'Hollow hold',cat:'Core',equip:'Ninguno',pattern:'Anti-extensión',reps:'20–40 seg',
 desc:'Isométrico de gimnasia. Tensión total del abdomen.',
 pasos:['Boca arriba, brazos y piernas estirados.','Eleva hombros y piernas formando una "banana".','Lumbar pegada al suelo.'],
 errores:['Si la lumbar se despega, sube brazos/piernas.','No aguantes la respiración.'],
 musculos:'Recto abdominal, transverso',riesgo:'Lumbar'},
{key:'l-sit',name:'L-sit',cat:'Core',equip:'Barra',pattern:'Isométrico',reps:'10–25 seg',
 desc:'Sostén con piernas en L, en paralelas o suelo. Abdomen y flexores brutales.',
 pasos:['Apoya las manos y eleva el cuerpo con las piernas rectas al frente.','Forma una L con el tronco y las piernas.','Aprieta el abdomen y aguanta.'],
 errores:['Empieza con rodillas dobladas (tuck).','Hombros abajo, lejos de las orejas.'],
 musculos:'Abdomen, flexores, tríceps',riesgo:'Hombro'},
{key:'windshield',name:'Limpiaparabrisas',cat:'Core',equip:'Ninguno',pattern:'Rotación',reps:'8–12 reps',
 desc:'Piernas que rotan de lado a lado como un limpiaparabrisas. Oblicuos.',
 pasos:['Boca arriba, brazos en cruz y piernas arriba.','Baja las piernas juntas hacia un lado sin tocar el suelo.','Sube y baja al otro lado.'],
 errores:['Controla, no dejes caer.','Hombros pegados al suelo.'],
 musculos:'Oblicuos, recto abdominal',riesgo:'Lumbar'},
// ═══════════════ CARDIO ═══════════════
{key:'burpees',name:'Burpees',cat:'Cardio',equip:'Ninguno',pattern:'Cuerpo completo',reps:'8–15 reps',
 desc:'El ejercicio de cuerpo completo definitivo. Fuerza + cardio intenso.',
 pasos:['Baja a cuclillas y apoya las manos.','Lanza los pies atrás a plancha (opcional: flexión).','Recoge los pies y salta con los brazos arriba.'],
 errores:['No hundas la lumbar en la plancha.','Amortigua la caída del salto.'],
 musculos:'Cuerpo completo',riesgo:'Muñeca · Rodilla · Lumbar'},
{key:'jumping-jacks',name:'Saltos de tijera',cat:'Cardio',equip:'Ninguno',pattern:'Cardio',reps:'40–60 seg',
 desc:'Clásico de calentamiento y cardio. Coordina brazos y piernas.',
 pasos:['De pie, salta abriendo piernas y subiendo los brazos.','Vuelve al centro con otro salto.','Ritmo constante.'],
 errores:['Amortigua con las rodillas.','Brazos completos arriba.'],
 musculos:'Cuerpo completo, cardio',riesgo:'Tobillo · Rodilla'},
{key:'rodillas-altas',name:'Rodillas altas',cat:'Cardio',equip:'Ninguno',pattern:'Cardio',reps:'30–45 seg',
 desc:'Correr en el sitio elevando las rodillas. Cardio y core.',
 pasos:['Corre en el sitio subiendo las rodillas a la cadera.','Apoya sobre el metatarso.','Brazos acompañando.'],
 errores:['No te eches atrás.','Sube de verdad las rodillas.'],
 musculos:'Flexores, gemelo, core',riesgo:'Rodilla · Tobillo'},
{key:'talones-gluteo',name:'Talones al glúteo',cat:'Cardio',equip:'Ninguno',pattern:'Cardio',reps:'30–45 seg',
 desc:'Correr en el sitio llevando los talones atrás. Cardio suave.',
 pasos:['Corre tocando el glúteo con los talones.','Tronco erguido.','Ritmo ágil.'],
 errores:['No te inclines al frente.','Apoyo suave.'],
 musculos:'Isquios, gemelo, cardio',riesgo:'Rodilla'},
{key:'sentadilla-salto',name:'Sentadilla con salto',cat:'Cardio',equip:'Ninguno',pattern:'Pliometría',reps:'10–15 reps',
 desc:'Sentadilla explosiva. Potencia de piernas y cardio.',
 pasos:['Baja a sentadilla.','Salta con fuerza extendiendo todo el cuerpo.','Cae suave y encadena.'],
 errores:['Amortigua flexionando.','Rodillas alineadas.'],
 musculos:'Cuádriceps, glúteo, gemelo',riesgo:'Rodilla · Tobillo'},
{key:'zancada-salto',name:'Zancada con salto',cat:'Cardio',equip:'Ninguno',pattern:'Pliometría',reps:'10–16 reps',
 desc:'Zancadas alternando piernas con salto. Potencia y cardio.',
 pasos:['En zancada, salta cambiando de pierna en el aire.','Cae suave en la nueva zancada.','Encadena con ritmo.'],
 errores:['Amortigua la caída.','Tronco estable, sin bambolearte.'],
 musculos:'Cuádriceps, glúteo',riesgo:'Rodilla · Tobillo'},
{key:'skater',name:'Saltos de patinador',cat:'Cardio',equip:'Ninguno',pattern:'Pliometría lateral',reps:'30–45 seg',
 desc:'Saltos laterales de pierna a pierna. Potencia lateral y equilibrio.',
 pasos:['Salta lateralmente cayendo sobre una pierna.','La otra pierna cruza por detrás.','Rebota al lado contrario.'],
 errores:['Amortigua con rodilla y cadera.','La rodilla no debe meterse.'],
 musculos:'Glúteo, cuádriceps, estabilizadores',riesgo:'Rodilla · Tobillo'},
{key:'tuck-jump',name:'Tuck jump',cat:'Cardio',equip:'Ninguno',pattern:'Pliometría',reps:'8–12 reps',
 desc:'Salto vertical llevando las rodillas al pecho. Potencia explosiva.',
 pasos:['Salta lo más alto posible.','Lleva las rodillas hacia el pecho en el aire.','Cae suave y encadena.'],
 errores:['Amortigua la caída.','No redondees la espalda.'],
 musculos:'Cuádriceps, glúteo, core',riesgo:'Rodilla · Tobillo'},
{key:'box-jump',name:'Salto al cajón',cat:'Cardio',equip:'Banco',pattern:'Pliometría',reps:'8–12 reps',
 desc:'Salto sobre un cajón. Potencia de piernas con caída controlada.',
 pasos:['Frente al cajón, flexiona y salta arriba.','Cae suave con las dos piernas sobre el cajón.','Baja con cuidado (mejor bajar que saltar abajo).'],
 errores:['Altura acorde a tu nivel.','Cae flexionando para amortiguar.'],
 musculos:'Cuádriceps, glúteo, gemelo',riesgo:'Rodilla · Tobillo'},
{key:'comba',name:'Saltar a la comba',cat:'Cardio',equip:'Comba',pattern:'Cardio',reps:'40–90 seg',
 desc:'Cardio eficiente y de bajo impacto si se hace con técnica.',
 pasos:['Salta con ambos pies, rebotes pequeños.','Gira la cuerda desde las muñecas.','Cae suave sobre el metatarso.'],
 errores:['Saltos bajos.','Codos pegados al cuerpo.'],
 musculos:'Gemelo, hombro, cardio',riesgo:'Tobillo · Rodilla'},
{key:'sprint-sitio',name:'Sprint en el sitio',cat:'Cardio',equip:'Ninguno',pattern:'Cardio',reps:'20–30 seg',
 desc:'Carrera máxima en el sitio para picos de intensidad (intervalos).',
 pasos:['Corre en el sitio lo más rápido posible.','Brazos activos, apoyo en metatarso.','Mantén el pico el tiempo marcado.'],
 errores:['No aguantes la respiración.','Tronco estable.'],
 musculos:'Piernas, cardio',riesgo:'Tobillo'},
{key:'bear-crawl',name:'Bear crawl',cat:'Cardio',equip:'Ninguno',pattern:'Cuerpo completo',reps:'30–45 seg',
 desc:'Desplazamiento a cuatro apoyos con rodillas elevadas. Core y cardio.',
 pasos:['A cuatro apoyos con las rodillas justo bajo la cadera, elevadas.','Avanza moviendo mano y pie contrarios.','Cadera baja y estable.'],
 errores:['No subas mucho la cadera.','Pasos cortos y controlados.'],
 musculos:'Core, hombro, cuádriceps',riesgo:'Muñeca'},
// ═══════════════ MOVILIDAD ═══════════════
{key:'gato-vaca',name:'Gato–Vaca',cat:'Movilidad',equip:'Ninguno',pattern:'Movilidad columna',reps:'8–10 ciclos',
 desc:'Movilidad de columna en cuadrupedia. Ideal para calentar la espalda.',
 pasos:['A cuatro apoyos, arquea la espalda arriba (gato).','Luego hunde la espalda y mira al frente (vaca).','Sincroniza con la respiración.'],
 errores:['Movimiento lento, vértebra a vértebra.','No fuerces el cuello.'],
 musculos:'Columna, core',riesgo:'—'},
{key:'perro-abajo',name:'Perro boca abajo',cat:'Movilidad',equip:'Ninguno',pattern:'Estiramiento',reps:'30–45 seg',
 desc:'Postura de V invertida. Estira toda la cadena posterior.',
 pasos:['Desde el suelo, eleva la cadera formando una V.','Empuja el pecho hacia los muslos.','Talones hacia el suelo, respira.'],
 errores:['No redondees la espalda.','Rodillas algo flexionadas si tiras de isquios.'],
 musculos:'Isquios, gemelo, hombro, espalda',riesgo:'Hombro'},
{key:'postura-nino',name:'Postura del niño',cat:'Movilidad',equip:'Ninguno',pattern:'Estiramiento',reps:'30–60 seg',
 desc:'Descanso activo que estira la espalda baja y las caderas.',
 pasos:['De rodillas, siéntate sobre los talones.','Lleva el tronco hacia delante, brazos estirados.','Relaja y respira profundo.'],
 errores:['Abre las rodillas si molesta la cadera.','No fuerces.'],
 musculos:'Lumbar, cadera, hombro',riesgo:'Rodilla'},
{key:'cobra',name:'Cobra',cat:'Movilidad',equip:'Ninguno',pattern:'Movilidad columna',reps:'20–30 seg',
 desc:'Extensión suave de columna. Contrarresta estar sentado.',
 pasos:['Boca abajo, manos bajo los hombros.','Empuja el pecho arriba con la cadera en el suelo.','Hombros lejos de las orejas.'],
 errores:['No fuerces la lumbar con dolor.','Codos ligeramente flexionados.'],
 musculos:'Flexores de cadera, abdomen (estiramiento)',riesgo:'Lumbar'},
{key:'world-greatest',name:'World\u2019s greatest stretch',cat:'Movilidad',equip:'Ninguno',pattern:'Estiramiento dinámico',reps:'5–6 por lado',
 desc:'Estiramiento dinámico completo: cadera, tronco y dorsal en un movimiento.',
 pasos:['Desde zancada, apoya la mano contraria dentro del pie.','Rota el otro brazo abriendo el pecho hacia el techo.','Vuelve y cambia de lado.'],
 errores:['Movimiento controlado.','Talón trasero activo.'],
 musculos:'Cadera, columna dorsal, isquios',riesgo:'Cadera'},
{key:'paloma',name:'Postura de la paloma',cat:'Movilidad',equip:'Ninguno',pattern:'Estiramiento',reps:'30–45 seg por lado',
 desc:'Estiramiento profundo del glúteo y rotadores de cadera.',
 pasos:['Lleva una pierna doblada al frente y estira la otra atrás.','Baja el tronco sobre la pierna delantera.','Respira y relaja la cadera.'],
 errores:['No fuerces la rodilla delantera.','Usa un cojín bajo el glúteo si molesta.'],
 musculos:'Glúteo, rotadores de cadera',riesgo:'Rodilla · Cadera'},
{key:'estiramiento-cuadriceps',name:'Estiramiento de cuádriceps',cat:'Movilidad',equip:'Ninguno',pattern:'Estiramiento',reps:'20–30 seg por lado',
 desc:'Estiramiento de pie del cuádriceps y flexor de cadera.',
 pasos:['De pie, lleva un talón hacia el glúteo.','Sujeta el tobillo con la mano.','Rodillas juntas, cadera al frente.'],
 errores:['No arquees la lumbar.','Usa apoyo si pierdes el equilibrio.'],
 musculos:'Cuádriceps, flexor de cadera',riesgo:'Rodilla'},
{key:'estiramiento-isquios',name:'Estiramiento de isquios',cat:'Movilidad',equip:'Ninguno',pattern:'Estiramiento',reps:'20–30 seg por lado',
 desc:'Estiramiento de la parte posterior del muslo.',
 pasos:['Sentado o de pie, una pierna estirada.','Lleva el tronco hacia el pie con la espalda recta.','Nota el estiramiento sin dolor.'],
 errores:['No redondees la espalda para llegar más.','Rodilla ligeramente suelta.'],
 musculos:'Isquiotibiales',riesgo:'Lumbar'},
{key:'noventa-noventa',name:'90/90 de cadera',cat:'Movilidad',equip:'Ninguno',pattern:'Movilidad cadera',reps:'8–10 por lado',
 desc:'Movilidad de rotación de cadera, útil para sentadilla y carrera.',
 pasos:['Sentado, ambas piernas a 90° (una delante, una al lado).','Gira las rodillas de un lado al otro controlando.','Pecho arriba.'],
 errores:['No fuerces el rango.','Lento y controlado.'],
 musculos:'Rotadores de cadera',riesgo:'Cadera · Rodilla'},
{key:'rotacion-toracica',name:'Rotación torácica',cat:'Movilidad',equip:'Ninguno',pattern:'Movilidad columna',reps:'8–10 por lado',
 desc:'Abre la columna dorsal. Clave si pasas horas sentado.',
 pasos:['A cuatro apoyos, una mano en la nuca.','Gira el codo hacia el techo abriendo el pecho.','Vuelve y repite antes de cambiar.'],
 errores:['Gira desde el tronco, no el cuello.','Cadera estable.'],
 musculos:'Columna dorsal, oblicuos',riesgo:'—'},
{key:'wall-angels',name:'Wall angels',cat:'Movilidad',equip:'Ninguno',pattern:'Movilidad hombro',reps:'10–12 reps',
 desc:'Deslizar los brazos por la pared como un ángel. Postura y hombro.',
 pasos:['Espalda y brazos pegados a la pared, codos a 90°.','Desliza los brazos arriba manteniendo el contacto.','Baja controlado sin despegar.'],
 errores:['No arquees la lumbar.','Mantén muñecas y codos en la pared.'],
 musculos:'Hombro, trapecio, dorsal',riesgo:'Hombro'},
{key:'circulos-hombro',name:'Círculos de hombro',cat:'Movilidad',equip:'Ninguno',pattern:'Movilidad hombro',reps:'10 por sentido',
 desc:'Calienta el hombro antes de empujar o traccionar.',
 pasos:['Brazos estirados a los lados.','Haz círculos pequeños que van creciendo.','Cambia de sentido.'],
 errores:['No encojas los hombros.','Movimiento controlado.'],
 musculos:'Deltoides, manguito rotador',riesgo:'Hombro'},
{key:'balanceo-pierna',name:'Balanceo de pierna',cat:'Movilidad',equip:'Ninguno',pattern:'Movilidad cadera',reps:'12–15 por pierna',
 desc:'Movilidad dinámica de cadera. Ideal antes de correr o entrenar pierna.',
 pasos:['Sujétate a un apoyo, balancea una pierna al frente y atrás.','Tronco estable.','Aumenta el rango progresivamente.'],
 errores:['No arquees la lumbar.','Controla el balanceo.'],
 musculos:'Flexores y extensores de cadera',riesgo:'Cadera'},
{key:'movilidad-tobillo',name:'Movilidad de tobillo',cat:'Movilidad',equip:'Ninguno',pattern:'Movilidad tobillo',reps:'8–10 por lado',
 desc:'Lleva la rodilla sobre la punta del pie. Clave para sentadilla profunda.',
 pasos:['En zancada corta frente a una pared.','Lleva la rodilla al frente sobre los dedos sin despegar el talón.','Vuelve y repite.'],
 errores:['Talón siempre pegado al suelo.','Rodilla en línea con el pie.'],
 musculos:'Tobillo, gemelo (movilidad)',riesgo:'Tobillo'},
{key:'respiracion',name:'Respiración guiada',cat:'Movilidad',equip:'Ninguno',pattern:'Recuperación',reps:'1–2 min',
 desc:'Cierre del entreno: baja pulsaciones y mejora la recuperación.',
 pasos:['Tumbado o sentado cómodo.','Inhala 4 segundos por la nariz.','Exhala 6 segundos lento por la boca.'],
 errores:['No fuerces la respiración.','Alarga la exhalación.'],
 musculos:'Diafragma (relajación)',riesgo:'—'}
];
